'use client';

import React, { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import {
  ArrowRight, ShieldCheck, Zap, BarChart3,
  AlertTriangle, GitBranch, PenTool, FileText,
  CheckCircle2, XCircle, Users, Clock
} from 'lucide-react';
import Image from 'next/image';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

if (typeof window !== 'undefined') {
  gsap.registerPlugin(ScrollTrigger);
}

// ─── Problem section ─────────────────────────────────────────────────────────
const PROBLEMS = [
  {
    icon: <XCircle size={18} className="text-red-400/80" />,
    title: 'Peer Evaluation Forms',
    description: 'Teammates rate each other once, at the end. Subjective, gameable with reciprocal high ratings, and too late to fix anything.',
  },
  {
    icon: <XCircle size={18} className="text-red-400/80" />,
    title: 'Task Boards (Trello / Jira)',
    description: 'Requires everyone to remember to log work — the exact self-report step free-riders skip.',
  },
  {
    icon: <XCircle size={18} className="text-red-400/80" />,
    title: 'Status Check-in Bots',
    description: 'A Slack bot pings members to report progress. Adds a new habit — exactly the kind of friction that gets ignored first.',
  },
  {
    icon: <XCircle size={18} className="text-red-400/80" />,
    title: 'Instructor Spot-checks',
    description: 'Doesn\'t scale past a handful of teams, and only samples a moment in time.',
  },
];

// ─── How it works steps ───────────────────────────────────────────────────────
const STEPS = [
  {
    step: '01',
    title: 'Link your accounts',
    description: 'Connect GitHub, Figma, and/or Google Docs once. Under 60 seconds per source. Nothing to configure, no docs required.',
    sources: ['GitHub', 'Figma', 'Google Docs'],
  },
  {
    step: '02',
    title: 'Work exactly as you normally do',
    description: 'Commit code, edit designs, revise documents. Free-Rider Tracker reads these activity trails automatically — no new habit introduced.',
    sources: ['Commits', 'Design edits', 'Doc revisions'],
  },
  {
    step: '03',
    title: 'Group forms automatically',
    description: 'When a submission points at a shared repo, Figma file, or Google Doc, the group is created from contributors/editors. No invite step needed.',
    sources: ['Auto-detected', 'No manual setup'],
  },
  {
    step: '04',
    title: 'Get the Group Insight Report',
    description: 'Contribution % per member, an activity timeline, and plain-language insights — rendered in under 5 seconds. Objective. Independently verifiable.',
    sources: ['Per-source breakdown', 'Activity timeline', 'Plain-language insights'],
  },
];

// ─── Solution comparison ──────────────────────────────────────────────────────
const COMPARISON = [
  { dimension: 'Data source', existing: 'Self-report — forms, check-ins, task boards', ours: 'Passive activity generated by real work (commits, doc edits, timestamps)' },
  { dimension: 'Adoption friction', existing: 'High — a new habit every member must keep', ours: 'Near zero — nothing new to log; reads what already exists' },
  { dimension: 'Timing', existing: 'End-of-project or periodic snapshots', ours: 'Continuous — reconstructed at any point from the full history' },
  { dimension: 'Bias', existing: 'Subjective, socially influenced, reciprocity-gameable', ours: 'Objective and independently verifiable from source platforms' },
  { dimension: 'Design assumption', existing: 'Assumes people will self-report honestly', ours: 'Assumes they won\'t — and designs around that instead' },
];

// ─── Feature cards ────────────────────────────────────────────────────────────
const FEATURES = [
  {
    icon: <GitBranch size={20} className="text-white/70" />,
    title: 'Source Adapter Architecture',
    description:
      'Every provider — GitHub, Figma, Google Docs — plugs into the same two-function contract: fetchRawActivity and normalize. Adding a new source is a ~40-line adapter file, not a new pipeline.',
    tag: 'Architecture',
  },
  {
    icon: <ShieldCheck size={20} className="text-white/70" />,
    title: 'Read-only by Design',
    description:
      'We request the minimum possible OAuth scopes across all providers. We read metadata — timestamps, diff sizes, edit counts — never file contents. Linking is opt-in and revocable.',
    tag: 'Privacy',
  },
  {
    icon: <Zap size={20} className="text-white/70" />,
    title: 'Zero Ongoing Input',
    description:
      'No screen in the product ever asks a member to manually log or rate work. Once accounts are linked, contribution is measured automatically at every submission.',
    tag: 'Zero friction',
  },
  {
    icon: <BarChart3 size={20} className="text-white/70" />,
    title: 'Per-source Breakdown',
    description:
      'Combining code commits with design versions and doc revisions in one blended score is misleading. Free-Rider Tracker shows each source\'s share separately so nothing is hidden.',
    tag: 'Transparency',
  },
  {
    icon: <Users size={20} className="text-white/70" />,
    title: 'Individual Profiles',
    description:
      'Every member gets a verified contribution history reusable as a portfolio record — across every group they\'ve been a part of.',
    tag: 'Profiles',
  },
  {
    icon: <Clock size={20} className="text-white/70" />,
    title: 'Activity Timeline',
    description:
      'See not just who contributed, but when. Identify who carried the project in its final hours versus who drove it throughout — plain language, no jargon.',
    tag: 'Timeline',
  },
];

const dashboardTabs = [
  {
    id: 1,
    title: 'Passive Ingestion',
    src: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?auto=format&fit=crop&q=80&w=3840',
    alt: 'Reads native source activity from GitHub, Figma, and Docs. Zero manual check-ins required.',
  },
  {
    id: 2,
    title: 'Insight Reports',
    src: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=3840',
    alt: 'Generates objective contribution percentages, timelines, and plain-language insights instantly.',
  },
  {
    id: 3,
    title: 'Zero Setup',
    src: 'https://images.unsplash.com/photo-1507238692062-71092e071e62?auto=format&fit=crop&q=80&w=3840',
    alt: 'Members link accounts in under 60 seconds. Groups form automatically from shared repos.',
  },
  {
    id: 4,
    title: 'Un-cheatable',
    src: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=3840',
    alt: 'Avoids forms and peer reviews. Treats self-reporting as unreliable and bypasses bias entirely.',
  },
];

export default function FeaturesDetail() {
  const sectionRef = useRef<HTMLDivElement>(null);
  const [currentSlide, setCurrentSlide] = useState(0);

  useEffect(() => {
    const ctx = gsap.context(() => {
      gsap.utils.toArray<HTMLElement>('.reveal-up').forEach((el) => {
        gsap.fromTo(
          el,
          { y: 40, opacity: 0 },
          {
            y: 0,
            opacity: 1,
            duration: 0.9,
            ease: 'power3.out',
            scrollTrigger: {
              trigger: el,
              start: 'top 85%',
            },
          }
        );
      });
    }, sectionRef);

    const interval = setInterval(() => {
      setCurrentSlide((prev) => (prev === dashboardTabs.length - 1 ? 0 : prev + 1));
    }, 5000);

    return () => {
      ctx.revert();
      clearInterval(interval);
    };
  }, []);

  return (
    <div ref={sectionRef} className="relative bg-black text-white overflow-hidden">
      <style dangerouslySetInnerHTML={{__html:`
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');
        .section-font { font-family:'Inter',-apple-system,BlinkMacSystemFont,sans-serif; }
        .comparison-row:nth-child(odd) { background: rgba(255,255,255,0.02); }
        .feature-card-hover { transition: all 0.25s ease; }
        .feature-card-hover:hover { background: rgba(255,255,255,0.06); border-color: rgba(255,255,255,0.15); transform: translateY(-2px); }
      `}} />

      {/* ──────── PROBLEM SECTION ──────── */}
      <section id="problem" className="section-font py-24 lg:py-32 border-t border-white/5">
        <div className="max-w-7xl mx-auto px-5 sm:px-8 lg:px-12">
          <div className="reveal-up max-w-2xl mb-16">
            <span className="inline-block text-xs font-semibold tracking-widest uppercase text-white/30 mb-4">The Problem</span>
            <h2 className="text-4xl sm:text-5xl font-bold tracking-tight leading-tight">
              Self-report is the load-bearing weakness.
            </h2>
            <p className="mt-5 text-white/50 text-lg leading-relaxed">
              Group work — in classrooms, hackathons, and workplaces — runs on one quiet assumption: that every member will honestly report what they contributed. That assumption fails constantly.
            </p>
            <p className="mt-4 text-white/40 text-base leading-relaxed">
              A survey of 205 students across an Australian university found free-riding was the <em>single greatest concern</em> students raised about group work, across every discipline. It is not a rare edge case.
            </p>
          </div>

          <div className="reveal-up grid sm:grid-cols-2 gap-4">
            {PROBLEMS.map((p) => (
              <div
                key={p.title}
                className="flex gap-4 p-6 rounded-2xl border border-white/5 bg-white/[0.02]"
              >
                <div className="mt-0.5 shrink-0">{p.icon}</div>
                <div>
                  <h3 className="font-semibold text-white/80 mb-1">{p.title}</h3>
                  <p className="text-sm text-white/40 leading-relaxed">{p.description}</p>
                </div>
              </div>
            ))}
          </div>

          <div className="reveal-up mt-10 p-6 rounded-2xl border border-amber-500/20 bg-amber-500/5 flex gap-4">
            <AlertTriangle size={18} className="text-amber-400/70 shrink-0 mt-0.5" />
            <p className="text-sm text-white/50 leading-relaxed">
              <span className="text-amber-300/80 font-semibold">The cost isn't just fairness on paper.</span>{' '}
              Students report receiving the same grade as teammates who produced a fraction of the output. The students most likely to free-ride are also the least likely to be caught — because agreeableness and conscientiousness are significant negative predictors of social loafing, traits self-report systems are blind to.
            </p>
          </div>
        </div>
      </section>

      {/* ──────── SOLUTION / COMPARISON ──────── */}
      <section id="solution" className="section-font py-24 lg:py-32 border-t border-white/5">
        <div className="max-w-7xl mx-auto px-5 sm:px-8 lg:px-12">
          <div className="reveal-up max-w-2xl mb-16">
            <span className="inline-block text-xs font-semibold tracking-widest uppercase text-white/30 mb-4">Our Solution</span>
            <h2 className="text-4xl sm:text-5xl font-bold tracking-tight leading-tight">
              Observe, don&apos;t ask.
            </h2>
            <p className="mt-5 text-white/50 text-lg leading-relaxed">
              Instead of asking anyone to log, report, or check in, Free-Rider Tracker reconstructs true contribution from records that <em>already exist as a side effect of doing the work</em>. Members link their accounts once; from that point on, the system observes rather than asks.
            </p>
          </div>

          {/* Comparison table */}
          <div className="reveal-up overflow-x-auto rounded-2xl border border-white/8">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-white/8">
                  <th className="text-left px-6 py-4 text-white/30 font-semibold text-xs uppercase tracking-widest w-1/4">Dimension</th>
                  <th className="text-left px-6 py-4 text-red-400/60 font-semibold text-xs uppercase tracking-widest w-[37.5%]">
                    <XCircle size={12} className="inline mr-1.5 mb-0.5" /> Existing Tools
                  </th>
                  <th className="text-left px-6 py-4 text-green-400/70 font-semibold text-xs uppercase tracking-widest w-[37.5%]">
                    <CheckCircle2 size={12} className="inline mr-1.5 mb-0.5" /> Free-Rider Tracker
                  </th>
                </tr>
              </thead>
              <tbody>
                {COMPARISON.map((row) => (
                  <tr key={row.dimension} className="comparison-row border-b border-white/5 last:border-0">
                    <td className="px-6 py-4 text-white/50 font-medium">{row.dimension}</td>
                    <td className="px-6 py-4 text-white/35 leading-relaxed">{row.existing}</td>
                    <td className="px-6 py-4 text-white/70 leading-relaxed">{row.ours}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* ──────── HOW IT WORKS ──────── */}
      <section id="how-it-works" className="section-font py-24 lg:py-32 border-t border-white/5">
        <div className="max-w-7xl mx-auto px-5 sm:px-8 lg:px-12">
          <div className="reveal-up max-w-2xl mb-16">
            <span className="inline-block text-xs font-semibold tracking-widest uppercase text-white/30 mb-4">How it Works</span>
            <h2 className="text-4xl sm:text-5xl font-bold tracking-tight leading-tight">
              Four steps. Then step back.
            </h2>
            <p className="mt-5 text-white/50 text-lg leading-relaxed">
              The entire product is designed around a single constraint: never ask anyone to do anything they wouldn't do anyway.
            </p>
          </div>

          <div className="grid md:grid-cols-2 gap-5">
            {STEPS.map((s, i) => (
              <div
                key={s.step}
                className={`reveal-up rounded-2xl border border-white/8 p-7 bg-white/[0.02] flex flex-col gap-4 ${i === 0 ? 'md:col-span-2' : ''}`}
              >
                <div className="flex items-center gap-3">
                  <span className="font-mono text-xs font-bold text-white/20 tracking-widest">{s.step}</span>
                  <div className="flex-1 h-px bg-white/5" />
                </div>
                <h3 className="text-xl font-semibold text-white">{s.title}</h3>
                <p className="text-white/45 leading-relaxed text-sm">{s.description}</p>
                <div className="flex flex-wrap gap-2 mt-1">
                  {s.sources.map((src) => (
                    <span key={src} className="inline-flex items-center px-2.5 py-1 rounded-lg bg-white/5 border border-white/8 text-xs text-white/50 font-medium">
                      {src}
                    </span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ──────── FEATURES CAROUSEL ──────── */}
      <section id="features" className="section-font py-24 lg:py-32 border-t border-white/5">
        <div className="max-w-7xl mx-auto px-5 sm:px-8 lg:px-12">
          <div className="reveal-up text-left mb-16 max-w-2xl">
            <span className="inline-block text-xs font-semibold tracking-widest uppercase text-white/30 mb-4">Features</span>
            <h2 className="text-4xl sm:text-5xl font-bold tracking-tight">
              Absolute clarity,<br />mathematically derived.
            </h2>
            <p className="mt-5 text-white/50 text-lg leading-relaxed">
              The frictionless architecture that makes Free-Rider Tracker fundamentally un-cheatable.
            </p>
          </div>

          {/* Image carousel */}
          <div className="reveal-up relative h-[55vh] md:h-[65vh] w-full mb-12 perspective-1000">
            <div className="absolute inset-0 flex items-center justify-center">
              {dashboardTabs.map((tab, index) => {
                const position = index - currentSlide;
                const isActive = position === 0;
                const zIndex = isActive ? 30 : 20 - Math.abs(position);
                let displayPosition = position;
                if (position > 1) displayPosition -= dashboardTabs.length;
                if (position < -2) displayPosition += dashboardTabs.length;
                const translateX = displayPosition * 80;
                const scale = isActive ? 1 : 0.85;
                const opacity = Math.abs(displayPosition) > 1 ? 0 : 1;

                return (
                  <div
                    key={tab.id}
                    className={`absolute transition-all duration-700 ease-[cubic-bezier(0.25,1,0.5,1)] rounded-xl border cursor-pointer ${isActive ? 'border-white/20' : 'border-white/5'} ${isActive ? 'shadow-2xl shadow-white/5' : 'shadow-none'}`}
                    style={{ transform: `translateX(${translateX}%) scale(${scale})`, zIndex, opacity }}
                    onClick={() => setCurrentSlide(index)}
                  >
                    <div className="relative aspect-[16/9] w-[85vw] md:w-[60vw] max-w-5xl rounded-xl overflow-hidden bg-black">
                      <Image
                        src={tab.src}
                        alt={tab.alt}
                        fill
                        className="object-cover opacity-80 filter grayscale brightness-75 contrast-125"
                        priority={tab.id === 1}
                      />
                      {!isActive && (
                        <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" />
                      )}
                      {isActive && (
                        <div className="absolute inset-x-0 bottom-0 p-8 bg-gradient-to-t from-black via-black/80 to-transparent">
                          <h3 className="text-2xl font-semibold tracking-tight text-white mb-2">{tab.title}</h3>
                          <p className="text-white/60 text-sm max-w-lg">{tab.alt}</p>
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          <div className="flex justify-center gap-6 md:gap-12 mb-20">
            {dashboardTabs.map((tab, index) => (
              <button
                key={tab.id}
                onClick={() => setCurrentSlide(index)}
                className={`pb-2 text-xs uppercase tracking-widest font-semibold transition-all border-b-2 ${currentSlide === index ? 'text-white border-white' : 'text-white/30 border-transparent hover:text-white/60'}`}
              >
                {tab.title}
              </button>
            ))}
          </div>

          {/* Feature grid */}
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {FEATURES.map((f) => (
              <div
                key={f.title}
                className="reveal-up feature-card-hover rounded-2xl border border-white/8 bg-white/[0.02] p-6 flex flex-col gap-4"
              >
                <div className="flex items-start justify-between">
                  <div className="p-2.5 rounded-xl bg-white/5 border border-white/8">
                    {f.icon}
                  </div>
                  <span className="text-[10px] font-semibold tracking-widest uppercase text-white/25 px-2 py-1 rounded-lg bg-white/5 border border-white/8">
                    {f.tag}
                  </span>
                </div>
                <div>
                  <h3 className="font-semibold text-white mb-2">{f.title}</h3>
                  <p className="text-sm text-white/45 leading-relaxed">{f.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ──────── INTEGRATIONS SECTION ──────── */}
      <section className="section-font py-24 border-t border-white/5">
        <div className="max-w-7xl mx-auto px-5 sm:px-8 lg:px-12">
          <div className="reveal-up max-w-2xl mb-12">
            <span className="inline-block text-xs font-semibold tracking-widest uppercase text-white/30 mb-4">Integrations</span>
            <h2 className="text-4xl sm:text-5xl font-bold tracking-tight">
              One adapter pattern.<br />Three sources, one report.
            </h2>
            <p className="mt-5 text-white/50 text-lg leading-relaxed">
              Every provider plugs into the same interface. Adding Figma or Google Docs isn&apos;t a new pipeline — it&apos;s a new ~40-line adapter file plugged into a pipeline that already exists.
            </p>
          </div>

          <div className="reveal-up grid sm:grid-cols-3 gap-4">
            {[
              {
                icon: <GitBranch size={28} className="text-white/70" />,
                name: 'GitHub',
                desc: 'Commits, lines changed, files touched per member via REST API and webhook ingestion.',
                detail: ['Commits', 'Lines changed', 'Files touched', 'Contributor detection'],
              },
              {
                icon: <PenTool size={28} className="text-white/70" />,
                name: 'Figma',
                desc: 'File version history and edits per member via the Figma API.',
                detail: ['File versions', 'Edits per user', 'Timestamps', 'Auto-detected group'],
              },
              {
                icon: <FileText size={28} className="text-white/70" />,
                name: 'Google Docs',
                desc: 'Revision history per member via the Drive API.',
                detail: ['Revision history', 'Editor attribution', 'Timestamps', 'Doc-based grouping'],
              },
            ].map((src) => (
              <div key={src.name} className="feature-card-hover rounded-2xl border border-white/8 bg-white/[0.02] p-7">
                <div className="mb-5 p-3 rounded-xl bg-white/5 border border-white/8 w-fit">
                  {src.icon}
                </div>
                <h3 className="text-lg font-semibold text-white mb-2">{src.name}</h3>
                <p className="text-sm text-white/40 leading-relaxed mb-5">{src.desc}</p>
                <ul className="flex flex-col gap-2">
                  {src.detail.map((d) => (
                    <li key={d} className="flex items-center gap-2 text-xs text-white/50">
                      <CheckCircle2 size={11} className="text-green-400/60 shrink-0" />
                      {d}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ──────── CTA SECTION ──────── */}
      <section className="section-font py-24 lg:py-32 border-t border-white/5">
        <div className="max-w-7xl mx-auto px-5 sm:px-8 lg:px-12">
          <div className="reveal-up relative rounded-3xl border border-white/8 bg-white/[0.02] overflow-hidden p-12 lg:p-20 text-center">
            {/* Background glow */}
            <div className="absolute inset-0 pointer-events-none">
              <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[300px] bg-[radial-gradient(ellipse_at_top,rgba(255,255,255,0.06),transparent_70%)]" />
            </div>
            <div className="relative z-10">
              <span className="inline-block text-xs font-semibold tracking-widest uppercase text-white/30 mb-6">Get started</span>
              <h2 className="text-4xl sm:text-5xl font-bold tracking-tight text-white max-w-2xl mx-auto leading-tight">
                End the free-rider problem. Right now.
              </h2>
              <p className="mt-5 text-white/50 text-lg max-w-xl mx-auto leading-relaxed">
                Link your accounts in under a minute. Your group's contribution picture — objective, verifiable, and bias-free — is ready the moment you submit.
              </p>
              <div className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4">
                <Link
                  href="/sign-up"
                  id="cta-get-started"
                  className="inline-flex items-center gap-2 rounded-full px-8 py-3.5 text-sm font-semibold text-black bg-white hover:bg-white/90 transition-all active:scale-95"
                >
                  Get started free <ArrowRight size={15} />
                </Link>
                <Link
                  href="/sign-in"
                  id="cta-sign-in"
                  className="inline-flex items-center gap-2 rounded-full px-8 py-3.5 text-sm font-medium text-white/70 bg-white/5 border border-white/10 hover:bg-white/10 hover:text-white transition-all"
                >
                  Sign in
                </Link>
              </div>
              <p className="mt-6 text-xs text-white/25">
                Read-only scopes only · GitHub, Figma, Google Docs · NYC CodeQuest Batch 4
              </p>
            </div>
          </div>
        </div>
      </section>

    </div>
  );
}
